### ISSUE TITLE
Openshot: can't start the program

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#36]
From G+:

> just installed the new Openshot, as you said it would now work, but alas it is the same. NO LAUNCH. Here is the error from the command line:

``` bash: openshot: command not found ```﻿

**Comment by paulcarroty** [comment]
@kuboosoft @sergiomb2 like a problem with bad depends: 

```
# dnf install openshot
Last metadata expiration check: 0:03:26 ago on Fri May 27 03:39:03 2016.
Dependencies resolved.
=============================================================================
 Package            Arch   Version                          Repository  Size
=============================================================================
Installing:
 ImageMagick        x86_64 6.9.3.0-2.fc24                   fedora     170 k
 ImageMagick-c++    x86_64 6.9.3.0-2.fc24                   fedora     173 k
 ImageMagick-libs   x86_64 6.9.3.0-2.fc24                   fedora     2.2 M
 clang-libs         x86_64 3.8.0-1.fc24                     fedora     8.2 M
 ffmpeg-libs        x86_64 3.0.1-2.fc24                     unitedrpms 5.8 M
 fftw-libs-double   x86_64 3.3.4-7.fc24                     fedora     805 k
 fribidi            x86_64 0.19.7-2.fc24                    fedora      70 k
 lame-libs          x86_64 3.99.5-5.fc24                    unitedrpms 343 k
 libass             x86_64 0.13.1-2.fc24                    fedora      95 k
 libclc             x86_64 0.2.0-3.20160207gitdc330a3.fc24  fedora     5.0 M
 libopenshot        x86_64 0.1.1-2.fc24                     unitedrpms 307 k
 libopenshot-audio  x86_64 0.1.1-1.fc24                     unitedrpms 1.5 M
 libva              x86_64 1.7.0-1.fc24                     fedora      83 k
 libwmf-lite        x86_64 0.2.8.4-48.fc24                  fedora      73 k
 mesa-libOpenCL     x86_64 11.2.1-1.20160501.fc24           fedora     311 k
 ocl-icd            x86_64 2.2.8-3.git20151217.0122332.fc24 fedora      46 k
 openshot           noarch 2.0.7-2.fc24                     unitedrpms  79 M
 python-qt5-rpm-macros
                    noarch 5.6-1.fc24                       fedora      12 k
 python3-httplib2   noarch 0.9.2-2.fc24                     fedora     107 k
 python3-libopenshot
                    x86_64 0.1.1-2.fc24                     unitedrpms 338 k
 python3-qt5        x86_64 5.6-1.fc24                       fedora     4.0 M
 python3-sip        x86_64 4.18-1.fc24                      fedora     126 k
 schroedinger       x86_64 1.0.11-10.fc24                   fedora     325 k
 x264-libs          x86_64 0.148-2.20160420git3b70645.fc24  unitedrpms 356 k
 x265-libs          x86_64 1.9-1.20160221git40ba1eb.fc24    unitedrpms 2.1 M
 xvidcore           x86_64 1.3.4-1.fc24                     unitedrpms 690 k
Upgrading:
 mesa-libgbm        x86_64 11.2.1-1.20160501.fc24           fedora      58 k

Transaction Summary
=============================================================================
Install  26 Packages
Upgrade   1 Package

Total size: 112 M
Total download size: 79 M
Is this ok [y/N]: y
Downloading Packages:
................................................
Total                                        2.4 MB/s |  79 MB     00:32     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib/rpm/macros.d/macros.pyqt5 from install of python-qt5-rpm-macros-5.6-1.fc24.noarch conflicts with file from package python-qt5-5.5.1-17.fc24.x86_64

Error Summary
-------------

```

**Comment by paulcarroty** [comment]
Other log from [G+](https://plus.google.com/104617077706179713070/posts/hSiYxFAZAaX):

```
logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.7', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/launch.py", line 69, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/classes/app.py", line 144, in _init_
      logger:ERROR from windows.main_window import MainWindow
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 41, in <module>
      logger:ERROR from windows.views.timeline_webview import TimelineWebView
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/windows/views/timeline_webview.py", line 38, in <module>
      logger:ERROR from PyQt5.QtWebKitWidgets import QWebView
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by kuboosoft** [comment]
@paulcarroty .  I am testing some changes

**Comment by sergiomb2** [comment]
new kdenlive-16.04.1-2.fc24 and openshot-2.0.7-3.fc24 should be on all mirrors in a few minutes , please test it !

**Comment by theaudiobible** [comment]
For Fedora 24:
dnf install python3-qt5-webkit

**Comment by paulcarroty** [comment]
@theaudiobible don't need because `python3-qt5-webkit` was added as dependency.

**Comment by theaudiobible** [comment]
@paulcarroty - I found that I needed to install it for Fedora 24 64-bit.  I got the error No module named 'PyQt5.QtWebKitWidgets' after installing openshot-2.0.7-2.fc24.noarch, that's how I found this page.

**Comment by paulcarroty** [comment]
@theaudiobible the latest version in repository - `2.0.7-6`:

```
# dnf info openshot
...
Available Packages
Name        : openshot
Arch        : noarch
Epoch       : 0
Version     : 2.0.7
Release     : 6.fc25
Size        : 79 M
Repo        : unitedrpms
Summary     : Create and edit videos and movies
URL         : http://www.openshotvideo.com/
License     : GPLv3+
...
```

**Comment by theaudiobible** [comment]
@paulcarroty my apologies - I was using rpmfusion-free repo.  Thanks for your help.
